services:
  kubernetes:
    build:
      context: ./devcontainers/kubernetes
      dockerfile: Dockerfile
    image: ghcr.io/shanmeistro/simple-shell-kubernetes:latest
    container_name: simple-shell-kubernetes
    working_dir: /workspaces/simple-shell
    volumes:
      - .:/workspaces/simple-shell
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true

  ansible-aap:
    build:
      context: ./devcontainers/ansible-aap
      dockerfile: Dockerfile
    image: ghcr.io/shanmeistro/simple-shell-ansible-aap:latest
    container_name: simple-shell-ansible-aap
    working_dir: /workspaces/simple-shell
    volumes:
      - .:/workspaces/simple-shell
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true

  rhel-lab:
    build:
      context: ./devcontainers/rhel-lab
      dockerfile: Dockerfile
    image: ghcr.io/shanmeistro/simple-shell-rhel-lab:latest
    container_name: simple-shell-rhel-lab
    working_dir: /workspaces/simple-shell
    volumes:
      - .:/workspaces/simple-shell
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
