"""
Configuration templates for shell environment
"""

class Templates:
    """Configuration templates for various shell components"""
    
    @staticmethod
    def get_zshrc():
        """Get .zshrc template content"""
        return '''# ===============================================================
# Simple Shell Environment - Zsh Configuration
# Generated by simple-shell installer
# ===============================================================

# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Set theme to Powerlevel10k
ZSH_THEME="powerlevel10k/powerlevel10k"

# Enable useful plugins
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
    extract
    z
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Load Powerlevel10k instant prompt (should stay close to the top)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load Powerlevel10k configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# ===============================================================
# Environment Variables
# ===============================================================
export LANG=en_US.UTF-8
export EDITOR='vim'
export PAGER='less'

# Add local bin to PATH
export PATH="$HOME/.local/bin:$PATH"

# ===============================================================
# Platform-specific configurations
# ===============================================================
case "$OSTYPE" in
  linux*)
    # Linux-specific settings
    export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
    ;;
  darwin*)
    # macOS-specific settings
    if command -v brew >/dev/null 2>&1; then
      # Add Homebrew to PATH
      if [[ -d "/opt/homebrew" ]]; then
        export PATH="/opt/homebrew/bin:$PATH"
      fi
    fi
    
    # Use GNU tools if available
    if command -v gls >/dev/null 2>&1; then
      alias ls='gls --color=auto'
    fi
    ;;
  msys*|cygwin*)
    # Windows/WSL-specific settings
    ;;
esac

# ===============================================================
# Custom Aliases
# ===============================================================
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Safe file operations
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Git aliases (if git plugin doesn't provide these)
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline'

# Development aliases
alias py='python3'
alias pip='pip3'
alias serve='python3 -m http.server'

# System information
alias myip='curl -s https://ipinfo.io/ip'
alias weather='curl -s wttr.in'

# ===============================================================
# Custom Functions
# ===============================================================

# Create directory and change into it
mkcd() {
    mkdir -p "$1" && cd "$1"
}

# Extract various archive formats
extract() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Find and kill process by name
killbyname() {
    if [ -z "$1" ]; then
        echo "Usage: killbyname <process_name>"
        return 1
    fi
    
    local pids=$(pgrep -f "$1")
    if [ -n "$pids" ]; then
        echo "Killing processes matching '$1':"
        echo "$pids" | xargs ps -p
        echo "$pids" | xargs kill
    else
        echo "No processes found matching '$1'"
    fi
}

# Quick backup function
backup() {
    if [ -z "$1" ]; then
        echo "Usage: backup <file_or_directory>"
        return 1
    fi
    
    local timestamp=$(date +"%Y%m%d_%H%M%S")
    local backup_name="${1}_backup_${timestamp}"
    
    if [ -d "$1" ]; then
        tar czf "${backup_name}.tar.gz" "$1"
        echo "Directory backed up to: ${backup_name}.tar.gz"
    else
        cp "$1" "$backup_name"
        echo "File backed up to: $backup_name"
    fi
}

# ===============================================================
# History Configuration
# ===============================================================
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_VERIFY
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS

# ===============================================================
# Zsh Options
# ===============================================================
setopt AUTO_CD              # Change directory just by typing directory name
setopt CORRECT              # Spell check commands
setopt AUTO_LIST            # Automatically list choices on ambiguous completion
setopt AUTO_MENU            # Show completion menu on successive tab press
setopt AUTO_PUSHD           # Push the current directory visited on to the stack
setopt PUSHD_IGNORE_DUPS    # Don't push multiple copies of the same directory
setopt PUSHD_MINUS          # Reference stack entries with "-"

# ===============================================================
# Custom Key Bindings
# ===============================================================
bindkey "^[[1;5C" forward-word    # Ctrl+Right
bindkey "^[[1;5D" backward-word   # Ctrl+Left
bindkey "^[[3~" delete-char       # Delete key

# ===============================================================
# Load additional configurations
# ===============================================================

# Load custom local configurations if they exist
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Load work-specific configurations if they exist
[[ -f ~/.zshrc.work ]] && source ~/.zshrc.work

echo "🚀 Simple Shell Environment loaded successfully!"
'''

    @staticmethod
    def get_p10k_config():
        """Get a comprehensive P10k configuration"""
        return '''# ===============================================================
# Simple Shell Environment - Powerlevel10k Configuration
# Generated by simple-shell installer
# ===============================================================

# Temporarily change options
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required
  autoload -Uz is-at-least && is-at-least 5.1 || return

  # ===============================================================
  # Basic Layout Configuration
  # ===============================================================
  
  # The list of segments shown on the left
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # OS identifier
    dir                     # Current directory
    vcs                     # Git repository status
    prompt_char             # Prompt symbol
  )

  # The list of segments shown on the right
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # Exit code of the last command
    command_execution_time  # Duration of the last command
    background_jobs         # Presence of background jobs
    python_version         # Python version
    node_version           # Node.js version
    time                   # Current time
  )

  # ===============================================================
  # Instant Prompt Mode
  # ===============================================================
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # ===============================================================
  # Prompt Character Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'

  # ===============================================================
  # Directory Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  
  # Don't shorten directories that are one of the anchors
  local anchor_files=(
    .bzr
    .citc
    .git
    .hg
    .node-version
    .python-version
    .go-version
    .ruby-version
    .lua-version
    .java-version
    .perl-version
    .php-version
    .tool-versions
    .shorten_folder_marker
    .svn
    .terraform
    CVS
    Cargo.toml
    composer.json
    go.mod
    package.json
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"

  # ===============================================================
  # VCS (Git) Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=39
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=244
  
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'

  # ===============================================================
  # Status Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=70
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✓'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✗'

  # ===============================================================
  # Command Execution Time
  # ===============================================================
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=101
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # ===============================================================
  # Background Jobs
  # ===============================================================
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=37
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='⚙'

  # ===============================================================
  # Time Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=66
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # ===============================================================
  # OS Icon Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7

  # ===============================================================
  # Python Version Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_PYTHON_ICON='\U1F40D'  # 🐍
  typeset -g POWERLEVEL9K_PYTHON_VERSION_FOREGROUND=37

  # ===============================================================
  # Node Version Configuration
  # ===============================================================
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70

  # ===============================================================
  # Transient Prompt
  # ===============================================================
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  # ===============================================================
  # Advanced Features
  # ===============================================================
  
  # Show disk usage when directory takes too long to scan
  typeset -g POWERLEVEL9K_VCS_LOADING_TEXT=''
  
  # Git status formatter
  function my_git_formatter() {
    emulate -L zsh
    
    if [[ -n $P9K_CONTENT ]]; then
      typeset -g my_git_format=$P9K_CONTENT
      return
    fi
    
    if (( $1 )); then
      my_git_format='%196F✗'
    else
      my_git_format='%076F✓'
    fi
    
    (( $#_P9K_GITSTATUS_VCS_STATUS_STAGED )) && my_git_format+=' %178F+${#_P9K_GITSTATUS_VCS_STATUS_STAGED}'
    (( $#_P9K_GITSTATUS_VCS_STATUS_UNSTAGED )) && my_git_format+=' %196F!${#_P9K_GITSTATUS_VCS_STATUS_UNSTAGED}'
    (( $#_P9K_GITSTATUS_VCS_STATUS_UNTRACKED )) && my_git_format+=' %039F?${#_P9K_GITSTATUS_VCS_STATUS_UNTRACKED}'
  }
  functions -M my_git_formatter 2>/dev/null

  # ===============================================================
  # Color Customizations
  # ===============================================================
  
  # Default background color
  typeset -g POWERLEVEL9K_BACKGROUND=236
  
  # Separator configuration
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%244F\uE0B1'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%244F\uE0B3'
}

# Restore previous options
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
'''

    @staticmethod
    def get_alternative_install_script():
        """Get alternative installation script for systems without native Linux"""
        return '''#!/bin/bash

# ===============================================================
# Simple Shell Environment - Alternative Installation Methods
# ===============================================================

set -e

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

print_header() {
    echo -e "\\n${BLUE}============================================${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}============================================${NC}\\n"
}

print_step() {
    echo -e "\\n${GREEN}==> $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Check if we're in WSL/Docker/Cloud environment
detect_environment() {
    if [ -f /proc/version ]; then
        if grep -qi microsoft /proc/version; then
            echo "wsl"
        elif [ -f /.dockerenv ]; then
            echo "docker"
        else
            echo "linux"
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    else
        echo "unknown"
    fi
}

# Docker-based installation
run_docker_install() {
    print_header "Docker-based Installation"
    
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        echo "Visit: https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    print_step "Creating temporary Docker container for installation"
    
    # Create a temporary Dockerfile
    cat > /tmp/simple-shell-dockerfile << 'EOF'
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \\
    zsh \\
    git \\
    curl \\
    python3 \\
    fontconfig \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN python3 install.py --docker-mode

# Export configurations
CMD ["tar", "czf", "/tmp/simple-shell-config.tar.gz", "-C", "/root", ".oh-my-zsh", ".zshrc", ".p10k.zsh", ".local/share/fonts"]
EOF

    # Run installation in Docker
    docker build -f /tmp/simple-shell-dockerfile -t simple-shell-installer .
    docker run --rm -v $(pwd):/tmp/output simple-shell-installer
    
    print_step "Extracting configurations from Docker container"
    tar xzf simple-shell-config.tar.gz -C "$HOME"
    
    print_step "Cleaning up temporary files"
    rm -f /tmp/simple-shell-dockerfile simple-shell-config.tar.gz
    
    echo -e "${GREEN}✓ Docker-based installation completed!${NC}"
    echo -e "${YELLOW}Note: You may need to install fonts manually on your host system${NC}"
}

# Cloud-based installation (GitHub Codespaces, GitPod, etc.)
run_cloud_install() {
    print_header "Cloud Environment Installation"
    
    print_warning "Detected cloud environment. Some features may be limited."
    
    # Use curl to download and run the Python installer directly
    print_step "Downloading installer from GitHub"
    curl -fsSL https://raw.githubusercontent.com/your-repo/simple-shell/main/prototypes/python-installer/install.py > /tmp/simple-shell-install.py
    
    print_step "Running installation in cloud mode"
    python3 /tmp/simple-shell-install.py --cloud-mode
    
    rm -f /tmp/simple-shell-install.py
}

# WSL without Ubuntu
run_wsl_setup() {
    print_header "WSL Alternative Setup"
    
    print_step "Installing Ubuntu on WSL"
    
    cat << EOF
To install Ubuntu on WSL, run the following commands in PowerShell as Administrator:

1. Enable WSL:
   dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

2. Enable Virtual Machine Platform:
   dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

3. Restart your computer

4. Set WSL 2 as default:
   wsl --set-default-version 2

5. Install Ubuntu:
   wsl --install -d Ubuntu

6. After Ubuntu is installed, run this script again from within Ubuntu

EOF

    read -p "Have you completed the above steps? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        print_step "Proceeding with installation..."
        python3 install.py
    else
        print_warning "Please complete the WSL setup first, then run this script again"
        exit 0
    fi
}

# Main execution
main() {
    print_header "Simple Shell Environment - Alternative Installer"
    
    ENV=$(detect_environment)
    
    case $ENV in
        "wsl")
            print_step "WSL environment detected"
            python3 install.py
            ;;
        "docker")
            print_step "Docker environment detected"
            python3 install.py --docker-mode
            ;;
        "linux")
            print_step "Linux environment detected"
            python3 install.py
            ;;
        "macos")
            print_step "macOS environment detected"
            python3 install.py
            ;;
        *)
            print_warning "Unknown environment detected"
            echo "Choose installation method:"
            echo "1) Use Docker (requires Docker installed)"
            echo "2) Cloud environment setup"
            echo "3) Set up WSL first"
            echo "4) Try direct installation anyway"
            
            read -p "Enter choice (1-4): " choice
            case $choice in
                1) run_docker_install ;;
                2) run_cloud_install ;;
                3) run_wsl_setup ;;
                4) python3 install.py ;;
                *) print_error "Invalid choice"; exit 1 ;;
            esac
            ;;
    esac
}

# Run main function
main "$@"
'''