#!/usr/bin/env python3
"""
Configuration Templates
Provides configuration templates for different shells and frameworks
"""

from pathlib import Path
from typing import Dict, Optional

class ConfigTemplates:
    """Manages configuration templates for shells and frameworks"""
    
    def __init__(self):
        self.home = Path.home()
        self.config_dir = self.home / '.config'
    
    def get_zsh_config(self, framework: str = 'oh-my-zsh') -> str:
        """Generate .zshrc configuration"""
        if framework == 'oh-my-zsh':
            return self._get_zsh_ohmyzsh_config()
        else:
            return self._get_zsh_minimal_config()
    
    def _get_zsh_ohmyzsh_config(self) -> str:
        """Zsh configuration with Oh My Zsh"""
        return '''# Simple Shell Environment - Zsh with Oh My Zsh
# Generated by hybrid installer

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Set theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
    extract
    z
    docker
    kubectl
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Environment variables
export EDITOR=vim
export PAGER=less
export LANG=en_US.UTF-8

# Path modifications
export PATH="$HOME/.local/bin:$PATH"

# WSL2 specific settings
if grep -qi microsoft /proc/version 2>/dev/null; then
    export DISPLAY=${DISPLAY:-:0.0}
    
    # WSL2 aliases
    alias open='explorer.exe'
    alias code='code.exe'
    
    # WSL2 functions
    wsl-ip() { hostname -I | awk '{print $1}'; }
    win-home() { cd "/mnt/c/Users/$(whoami)"; }
fi

# General aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'

# Safe operations
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline'

# Development
alias py='python3'
alias serve='python3 -m http.server'

# Docker shortcuts
alias dc='docker-compose'
alias dps='docker ps'

# Custom functions
mkcd() { mkdir -p "$1" && cd "$1"; }

# History settings
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_VERIFY
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS

# Load Powerlevel10k config
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

echo "🚀 Zsh with Oh My Zsh loaded successfully!"
'''
    
    def _get_zsh_minimal_config(self) -> str:
        """Minimal Zsh configuration"""
        return '''# Simple Shell Environment - Minimal Zsh
# Generated by hybrid installer

# Basic settings
autoload -U compinit && compinit
autoload -U colors && colors

# Prompt
PROMPT='%{$fg[green]%}%n@%m%{$reset_color%} %{$fg[blue]%}%~%{$reset_color%} %# '

# Environment
export EDITOR=vim
export PAGER=less
export LANG=en_US.UTF-8
export PATH="$HOME/.local/bin:$PATH"

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# History
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_VERIFY
setopt SHARE_HISTORY

echo "🚀 Minimal Zsh loaded!"
'''
    
    def get_bash_config(self, framework: str = 'enhanced') -> str:
        """Generate .bashrc configuration"""
        if framework == 'bash-it':
            return self._get_bash_bashit_config()
        elif framework == 'starship':
            return self._get_bash_starship_config()
        elif framework == 'oh-my-posh':
            return self._get_bash_ohmyposh_config()
        else:
            return self._get_bash_enhanced_config()
    
    def _get_bash_bashit_config(self) -> str:
        """Bash configuration with Bash-it framework"""
        return '''# Simple Shell Environment - Bash with Bash-it
# Generated by hybrid installer

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Load Bash-it
if [ -f "$HOME/.bash_it/bash_it.sh" ]; then
    export BASH_IT="$HOME/.bash_it"
    export BASH_IT_THEME='powerline'
    source "$BASH_IT/bash_it.sh"
fi

# Environment variables
export EDITOR=vim
export PAGER=less
export LANG=en_US.UTF-8
export PATH="$HOME/.local/bin:$PATH"

# WSL2 specific settings
if grep -qi microsoft /proc/version 2>/dev/null; then
    export DISPLAY=${DISPLAY:-:0.0}
    alias open='explorer.exe'
    alias code='code.exe'
    wsl-ip() { hostname -I | awk '{print $1}'; }
fi

# History configuration
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
shopt -s checkwinsize

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'

# Color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

echo "🚀 Enhanced Bash with Bash-it loaded!"
'''
    
    def _get_bash_starship_config(self) -> str:
        """Bash configuration with Starship prompt"""
        return '''# Simple Shell Environment - Bash with Starship
# Generated by hybrid installer

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Initialize Starship prompt
if command -v starship > /dev/null; then
    eval "$(starship init bash)"
fi

# Environment variables
export EDITOR=vim
export PAGER=less
export LANG=en_US.UTF-8
export PATH="$HOME/.local/bin:$PATH"

# WSL2 specific settings
if grep -qi microsoft /proc/version 2>/dev/null; then
    export DISPLAY=${DISPLAY:-:0.0}
    alias open='explorer.exe'
    alias code='code.exe'
    wsl-ip() { hostname -I | awk '{print $1}'; }
fi

# History configuration
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
shopt -s checkwinsize

# Bash completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'

# Enhanced tools
if command -v bat > /dev/null; then
    alias cat='bat --paging=never'
fi

# Color support
if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

echo "🚀 Bash with Starship loaded!"
'''
    
    def _get_bash_ohmyposh_config(self) -> str:
        """Bash configuration with Oh My Posh"""
        return '''# Simple Shell Environment - Bash with Oh My Posh
# Generated by hybrid installer

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Initialize Oh My Posh
if command -v oh-my-posh > /dev/null; then
    eval "$(oh-my-posh init bash --config ~/.config/oh-my-posh/themes/1_shell.omp.json)"
fi

# Environment variables
export EDITOR=vim
export PAGER=less
export LANG=en_US.UTF-8
export PATH="$HOME/.local/bin:$PATH"

# WSL2 specific settings
if grep -qi microsoft /proc/version 2>/dev/null; then
    export DISPLAY=${DISPLAY:-:0.0}
    alias open='explorer.exe'
    alias code='code.exe'
    wsl-ip() { hostname -I | awk '{print $1}'; }
fi

# History configuration
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
shopt -s checkwinsize

# Bash completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'

# Color support
if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

echo "🚀 Bash with Oh My Posh (1_shell theme) loaded!"
'''
    
    def _get_bash_enhanced_config(self) -> str:
        """Enhanced bash configuration without frameworks"""
        return '''# Simple Shell Environment - Enhanced Bash
# Generated by hybrid installer

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Simple but effective prompt
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Environment variables
export EDITOR=vim
export PAGER=less
export LANG=en_US.UTF-8
export PATH="$HOME/.local/bin:$PATH"

# History configuration
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
shopt -s checkwinsize

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'

# Color support
if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

echo "🚀 Enhanced Bash loaded!"
'''
    
    def get_starship_config(self) -> str:
        """Generate starship configuration with nerd font symbols preset"""
        return '''# Simple Shell Environment - Starship Configuration
# Generated by hybrid installer
# Preset: Nerd Font Symbols

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = false
format = "in [$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"

[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold purple"
symbol = " "

[git_status]
format = "([$all_status$ahead_behind]($style)) "
style = "bold red"
conflicted = "⚡"
ahead = "⇡"
behind = "⇣"
divergned = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[python]
format = "via [$symbol$pyenv_prefix($version )($virtualenv )]($style)"
style = "bold yellow"
symbol = " "

[nodejs]
format = "via [$symbol($version )]($style)"
style = "bold green"
symbol = " "

[docker_context]
format = "via [$symbol$context]($style) "
style = "bold blue"
symbol = " "

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold white"

[os.symbols]
Ubuntu = " "
Windows = " "
macos = " "

[username]
show_always = true
format = "[$user]($style)@"
style_user = "bold blue"
style_root = "bold red"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold green"

[cmd_duration]
min_time = 2_000
format = "took [$duration]($style) "
style = "bold yellow"
'''
    
    def get_p10k_config(self) -> str:
        """Generate basic Powerlevel10k configuration"""
        return '''# Simple Shell Environment - Powerlevel10k Configuration
# Generated by hybrid installer

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
  autoload -Uz is-at-least && is-at-least 5.1 || return

  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    prompt_char
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    time
  )

  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  
  # Prompt character
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'

  # Directory
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=

  # VCS
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=39

  # OS icon
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7
}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
'''
    
    def write_config(self, config_path: Path, content: str) -> bool:
        """Write configuration to file with backup"""
        try:
            # Create backup if file exists
            if config_path.exists():
                backup_path = config_path.parent / f'{config_path.name}.backup'
                config_path.rename(backup_path)
            
            # Write new configuration
            config_path.parent.mkdir(parents=True, exist_ok=True)
            with config_path.open('w') as f:
                f.write(content)
            
            return True
        except Exception as e:
            print(f"Failed to write config {config_path}: {e}")
            return False