#!/usr/bin/env bash
set -e

# Load helper functions
source ./scripts/helpers.sh

print_header "Shell Environment Setup for WSL2"

# Function to detect if this is a fresh install vs existing system
detect_install_type() {
    if [ ! -f ~/.zshrc ] && [ ! -d ~/.oh-my-zsh ] && [ ! -f ~/.p10k.zsh ]; then
        echo "fresh"
    else
        echo "existing"
    fi
}

# Function to backup existing configurations
backup_existing_configs() {
    local backup_dir="$HOME/.config/shell-backup-$(date +%Y%m%d-%H%M%S)"
    
    print_header "Backing up existing shell configurations"
    
    local backed_up=()
    
    if [ -f ~/.zshrc ]; then
        mkdir -p "$backup_dir"
        cp ~/.zshrc "$backup_dir/" && backed_up+=(".zshrc")
    fi
    
    if [ -f ~/.p10k.zsh ]; then
        mkdir -p "$backup_dir"
        cp ~/.p10k.zsh "$backup_dir/" && backed_up+=(".p10k.zsh")
    fi
    
    if [ -d ~/.oh-my-zsh ]; then
        mkdir -p "$backup_dir"
        cp -r ~/.oh-my-zsh "$backup_dir/" && backed_up+=("oh-my-zsh/")
    fi
    
    if [ ${#backed_up[@]} -gt 0 ]; then
        print_success "Backup created at: $backup_dir"
        echo "Backed up: ${backed_up[*]}"
    else
        echo "No existing configurations found to backup"
    fi
}

# Function to install shell prerequisites
install_shell_prerequisites() {
    print_header "Installing Shell Prerequisites"
    
    sudo apt update
    sudo apt install -y \
        zsh \
        git \
        curl \
        wget \
        fontconfig
    
    print_success "Shell prerequisites installed"
}

# Function to install Oh My Zsh
install_oh_my_zsh() {
    print_header "Installing Oh My Zsh"
    
    if [ -d ~/.oh-my-zsh ]; then
        echo "Oh My Zsh already installed, skipping..."
        return 0
    fi
    
    # Install Oh My Zsh non-interactively
    RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    
    print_success "Oh My Zsh installed"
}

# Function to install Powerlevel10k
install_powerlevel10k() {
    print_header "Installing Powerlevel10k Theme"
    
    local p10k_dir="$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
    
    if [ -d "$p10k_dir" ]; then
        echo "Powerlevel10k already installed, updating..."
        git -C "$p10k_dir" pull
    else
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$p10k_dir"
    fi
    
    print_success "Powerlevel10k installed"
}

# Function to install useful Zsh plugins
install_zsh_plugins() {
    print_header "Installing Zsh Plugins"
    
    local plugins_dir="$HOME/.oh-my-zsh/custom/plugins"
    
    # zsh-autosuggestions
    if [ ! -d "$plugins_dir/zsh-autosuggestions" ]; then
        git clone https://github.com/zsh-users/zsh-autosuggestions "$plugins_dir/zsh-autosuggestions"
    fi
    
    # zsh-syntax-highlighting
    if [ ! -d "$plugins_dir/zsh-syntax-highlighting" ]; then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$plugins_dir/zsh-syntax-highlighting"
    fi
    
    print_success "Zsh plugins installed"
}

# Function to install recommended fonts
install_p10k_fonts() {
    print_header "Installing Powerlevel10k Fonts"
    
    local font_dir="$HOME/.local/share/fonts"
    mkdir -p "$font_dir"
    
    local fonts=(
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
    )
    
    for font_url in "${fonts[@]}"; do
        local font_name=$(basename "$font_url" | sed 's/%20/ /g')
        if [ ! -f "$font_dir/$font_name" ]; then
            echo "Downloading: $font_name"
            wget -q "$font_url" -O "$font_dir/$font_name"
        fi
    done
    
    # Refresh font cache
    fc-cache -fv > /dev/null 2>&1
    
    print_success "Fonts installed"
    echo "Note: Set your Windows Terminal font to 'MesloLGS NF' for best experience"
}

# Function to create .zshrc configuration
create_zshrc_config() {
    print_header "Creating Zsh Configuration"
    
    cat > ~/.zshrc << 'EOF'
# Simple Shell Environment - WSL2 Configuration
# Generated by WSL2 shell installer

# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Set theme to Powerlevel10k
ZSH_THEME="powerlevel10k/powerlevel10k"

# Enable useful plugins
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
    extract
    z
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# WSL2-specific configurations
export DISPLAY=${DISPLAY:-:0.0}

# Add local bin to PATH
export PATH="$HOME/.local/bin:$PATH"

# Environment variables
export LANG=en_US.UTF-8
export EDITOR='vim'
export PAGER='less'

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Safe file operations
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline'

# WSL2 specific aliases
alias open='explorer.exe'
alias code='code.exe'

# Development aliases
alias py='python3'
alias pip='pip3'
alias serve='python3 -m http.server'

# Docker aliases (if Docker is installed)
alias dc='docker-compose'
alias dps='docker ps'
alias di='docker images'

# Custom functions
mkcd() { mkdir -p "$1" && cd "$1"; }

# WSL2 specific functions
wsl-ip() {
    hostname -I | awk '{print $1}'
}

win-home() {
    cd "/mnt/c/Users/$(whoami)"
}

# History configuration
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_VERIFY
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS

# Zsh options
setopt AUTO_CD
setopt CORRECT
setopt AUTO_LIST
setopt AUTO_MENU
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_MINUS

echo "🚀 WSL2 Shell Environment loaded successfully!"
EOF
    
    print_success "Created .zshrc configuration"
}

# Function to create basic P10k configuration
create_p10k_config() {
    print_header "Creating Powerlevel10k Configuration"
    
    cat > ~/.p10k.zsh << 'EOF'
# WSL2 Powerlevel10k Configuration
# Generated by WSL2 shell installer

# Temporarily change options
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
  autoload -Uz is-at-least && is-at-least 5.1 || return

  # Left prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    prompt_char
  )

  # Right prompt segments  
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    time
  )

  # Instant prompt
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  
  # Prompt character
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'

  # Directory
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=

  # VCS (Git)
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=39

  # Status
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160

  # Command execution time
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=101

  # Background jobs
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=37

  # Time
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=66
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

  # OS icon
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7
}

# Restore options
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
EOF
    
    print_success "Created .p10k.zsh configuration"
}

# Function to set Zsh as default shell
set_default_shell() {
    print_header "Setting Zsh as Default Shell"
    
    local zsh_path=$(which zsh)
    local current_shell="$SHELL"
    
    if [ "$current_shell" = "$zsh_path" ]; then
        echo "Zsh is already the default shell"
        return 0
    fi
    
    echo "Current shell: $current_shell"
    echo "Zsh path: $zsh_path"
    
    if chsh -s "$zsh_path"; then
        print_success "Default shell changed to Zsh"
        echo "Please restart your terminal for the change to take effect"
    else
        echo "❌ Could not change default shell automatically"
        echo "Please run manually: chsh -s $zsh_path"
    fi
}

# Main installation flow
main() {
    local install_type=$(detect_install_type)
    
    echo "Detected installation type: $install_type"
    echo ""
    
    if [ "$install_type" = "existing" ]; then
        echo "Found existing shell configurations."
        read -p "Create backup before proceeding? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            backup_existing_configs
        fi
    fi
    
    # Core installation steps
    install_shell_prerequisites
    install_oh_my_zsh
    install_powerlevel10k
    install_zsh_plugins
    install_p10k_fonts
    create_zshrc_config
    create_p10k_config
    set_default_shell
    
    print_header "Shell Environment Setup Complete!"
    echo ""
    echo "🎉 Your WSL2 shell environment is ready!"
    echo ""
    echo "Next steps:"
    echo "1. Restart your terminal or run: exec zsh"
    echo "2. Set Windows Terminal font to 'MesloLGS NF'"
    echo "3. Configure Powerlevel10k: p10k configure (optional)"
    echo ""
    echo "WSL2-specific features included:"
    echo "• Windows integration aliases (open, code)"
    echo "• WSL2 utility functions (wsl-ip, win-home)"
    echo "• Optimized for Windows Terminal"
    echo ""
}

# Handle command line arguments
case "${1:-}" in
    --help|-h)
        echo "WSL2 Shell Environment Installer"
        echo ""
        echo "Usage: $0 [options]"
        echo ""
        echo "Options:"
        echo "  --help, -h    Show this help"
        echo ""
        echo "This script installs:"
        echo "• Zsh shell with Oh My Zsh framework"
        echo "• Powerlevel10k theme"
        echo "• Useful plugins (autosuggestions, syntax-highlighting)"
        echo "• MesloLGS NF fonts"
        echo "• WSL2-optimized configuration"
        echo ""
        exit 0
        ;;
esac

# Run main function
main "$@"